### ISSUE TITLE
Return type mismatch on ActionMailer::Base#mail annotation

### ISSUE THREAD

**Issue by sporeport** [Shopify/rbi-central#123]
### Problem

When we use the type annotations for action_mailer we get this error `Expected type ActionMailer::MessageDelivery, got type Mail::Message with value`. From what I can tell the `#mail` method returns a  `Mail::Message` type, [see return here](https://github.com/rails/rails/blob/main/actionmailer/lib/action_mailer/base.rb#L891) and [instance variable set here](https://github.com/rails/rails/blob/main/actionmailer/lib/action_mailer/base.rb#L636).

### Context

* Gem name: action_mailer
* Gem version: we are using action_mailer -v (6.1.6.1) (but I think this is applicable to later versions as well)
* Gem source: https://github.com/rails/rails/tree/main/actionmailer/lib/action_mailer
* Gem API doc: https://guides.rubyonrails.org/action_mailer_basics.html
* Tapioca version: 0.10.2
* Sorbet version: 0.5.10470

**Comment by KaanOzkan** [comment]
This signature was imported from `sorbet-typed`. Is your usage different than the one described in https://github.com/sorbet/sorbet-typed/pull/394?

**Comment by leifg** [comment]
If I recall correctly the return value varies based on environment and or mail configuration.

The workaround is using a `T.any` union:


```ruby
class SomethingMailer < ActionMailer::Base
  extend T::Sig

  sig { returns(T.any(ActionMailer::MessageDelivery, Mail::Message)) }
  def mail
    mail(to: 'test@example.com', subject: 'Test') { |format| format.text { render plain: 'empty' } }
  end
end
```

**Comment by leifg** [comment]
OK I got curious and it's a weird Rails thing. It's independent of configuration or environment.

Because the mailer methods are defined as instance methods (`def my_mail`) but are called as class methods (`MyMailer.my_mail`) action_mailer goes through the `method_missing` pipeline which passes the mailer in a `MessageDelivery` class and lazily generates the email by [instantiating the mailer and calling the instance method](https://github.com/rails/rails/blob/main/actionmailer/lib/action_mailer/message_delivery.rb#L127-L129).

You can verify that by going to the terminal and calling your mailer in the rails console (tested this in all Rails environments):

```ruby
m = MyMailer.my_mail; nil
m.class
=> ActionMailer::MessageDelivery
```

Meaning: the instance method `my_mail` will return a `Mail::Message` but the class method `self.my_mail` will return a `ActionMailer::MessageDelivery`.

So the actual Mailer class at runtime looks something like this:

```ruby
class MyMailer < ActionMailer::Base

  sig { returns(ActionMailer::MessageDelivery) }
  def self.my_mail
    ActionMailer::MessageDelivery.new(self, :my_mail, [])
  end

  sig { returns(Mail::Message) }
  def my_mail
    mail(to: "someone@example.com", subject: "Hello")
  end
end
```

It doesn't help that there is some evaluation magic happening, that automatically processes email on the rails console:

```ruby
MyMailer.my_mail
[2022-11-02T17:21:39.284+00:00] DEBUG: MyMailer#my_mail: processed outbound mail in 9.6ms
=> #<Mail::Message:442420, Multipart: true, Headers: <To: >, <Subject: Subject>, <Mime-Version: 1.0>, <Content-Type: multipart/mixed; boundary="--==_mimepart_6362a72344c1e_11950-35d"; charset=UTF-8>>
```

So it seems like the annotation should return a `Mail::Message`:

```ruby
class ActionMailer::Base
  sig { params(headers: T.untyped).returns(Mail::Message) }
  def mail(headers = nil, &block); end
end
```

but the generated RBI by `tapioca dsl` should return a `ActionMailer::MessageDelivery`:

```ruby
class MyMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def my_mail; end
  end
end
```

So +1 for changing the return type back to `Mail::Message` on the annotation.
